graph LR
AppModule -->ConfigModule
ConfigModule -->ConfigHostModule
ConfigHostModule -->ConfigModule
ConfigHostModule -->PrismaModule
PrismaModule -->ConfigModule
PrismaModule -->ConfigHostModule
PrismaModule -->JwtModule
JwtModule -->ConfigModule
JwtModule -->ConfigHostModule
JwtModule -->PrismaModule
JwtModule -->WinstonModule
WinstonModule -->ConfigModule
WinstonModule -->ConfigHostModule
WinstonModule -->PrismaModule
WinstonModule -->JwtModule
PrismaModule -->WinstonModule
ConfigHostModule -->JwtModule
ConfigHostModule -->WinstonModule
ConfigModule -->ConfigModule
ConfigModule -->PrismaModule
ConfigModule -->JwtModule
ConfigModule -->WinstonModule
AppModule -->StripeModule
StripeModule -->ConfigModule
StripeModule -->BookingModule
BookingModule -->WalletModule
WalletModule -->ConfigModule
WalletModule -->ConfigHostModule
WalletModule -->PrismaModule
WalletModule -->JwtModule
WalletModule -->WinstonModule
BookingModule -->ConfigModule
BookingModule -->ConfigHostModule
BookingModule -->PrismaModule
BookingModule -->JwtModule
BookingModule -->WinstonModule
StripeModule -->WalletModule
StripeModule -->ConfigHostModule
StripeModule -->PrismaModule
StripeModule -->JwtModule
StripeModule -->WinstonModule
AppModule -->PrismaModule
AppModule -->AuthModule
AuthModule -->JwtModule
AuthModule -->UsersModule
UsersModule -->ConfigModule
UsersModule -->ConfigHostModule
UsersModule -->PrismaModule
UsersModule -->JwtModule
UsersModule -->WinstonModule
AuthModule -->OtpModule
OtpModule -->PrismaModule
OtpModule -->ConfigModule
OtpModule -->ConfigHostModule
OtpModule -->JwtModule
OtpModule -->WinstonModule
AuthModule -->AgencyModule
AgencyModule -->CloudinaryModule
CloudinaryModule -->ConfigModule
CloudinaryModule -->ConfigHostModule
CloudinaryModule -->PrismaModule
CloudinaryModule -->JwtModule
CloudinaryModule -->WinstonModule
AgencyModule -->UsersModule
AgencyModule -->AdminModule
AdminModule -->ConfigModule
AdminModule -->ConfigHostModule
AdminModule -->PrismaModule
AdminModule -->JwtModule
AdminModule -->WinstonModule
AgencyModule -->ConfigModule
AgencyModule -->ConfigHostModule
AgencyModule -->PrismaModule
AgencyModule -->JwtModule
AgencyModule -->WinstonModule
AuthModule -->ConfigModule
AuthModule -->ConfigHostModule
AuthModule -->PrismaModule
AuthModule -->WinstonModule
AppModule -->UsersModule
AppModule -->OtpModule
AppModule -->AgencyModule
AppModule -->ProfileModule
ProfileModule -->CloudinaryModule
ProfileModule -->ConfigModule
ProfileModule -->ConfigHostModule
ProfileModule -->PrismaModule
ProfileModule -->JwtModule
ProfileModule -->WinstonModule
AppModule -->WinstonModule
AppModule -->AdminModule
AppModule -->CloudinaryModule
AppModule -->TripModule
TripModule -->ConfigModule
TripModule -->ConfigHostModule
TripModule -->PrismaModule
TripModule -->JwtModule
TripModule -->WinstonModule
AppModule -->WalletModule
AppModule -->BookingModule
AppModule -->TravellersModule
TravellersModule -->ConfigModule
TravellersModule -->ConfigHostModule
TravellersModule -->PrismaModule
TravellersModule -->JwtModule
TravellersModule -->WinstonModule
AppModule -->ChatModule
ChatModule -->ConfigModule
ChatModule -->ConfigHostModule
ChatModule -->PrismaModule
ChatModule -->JwtModule
ChatModule -->WinstonModule
AppModule -->ConversationModule
ConversationModule -->ConfigModule
ConversationModule -->ConfigHostModule
ConversationModule -->PrismaModule
ConversationModule -->JwtModule
ConversationModule -->WinstonModule
AppModule -->ConnectionModule
ConnectionModule -->ConversationModule
ConnectionModule -->ChatModule
ConnectionModule -->ConfigModule
ConnectionModule -->ConfigHostModule
ConnectionModule -->PrismaModule
ConnectionModule -->JwtModule
ConnectionModule -->WinstonModule
AppModule -->PaymentModule
PaymentModule -->BookingModule
PaymentModule -->ConfigModule
PaymentModule -->ConfigHostModule
PaymentModule -->PrismaModule
PaymentModule -->JwtModule
PaymentModule -->WinstonModule
AppModule -->ConfigHostModule
AppModule -->JwtModule
